### ISSUE TITLE
Description Cleanup 

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#106]
Feedback:

- [x] A3 Description not showing 
http://staging.withsix.com/p/Arma-3/mods/GO0RufGNQEi4QPZOlNuEaA/limited-contingent-of-soviet-troops-in-afghanistan
http://staging.withsix.com/p/Arma-3/mods/KOQSKgF24xG1UQAVF72WTA/ericj-weapons-pack

We are currently displaying API imported Descriptions beneath each other. 

- [x] Add Display Priority Description (Forums-> Steam>ThirdParty)
- [x] Add link to Source at the bottom of the Description

**Comment by sickboy** [comment]
@Sonsalt what is
> placement...

**Comment by sickboy** [comment]
I've split the optimization part to #120

**Comment by Sonsalt** [comment]
@sickboy 

nicely done, I would only improve on the "External links" a bit

Links to steamworkshop should be called "Steam Workshop"
Links to forums should be caled "Community Forum"

**Comment by sickboy** [comment]
@Sonsalt thanks, however don't forget to update the first post with actionable items..

**Comment by Sonsalt** [comment]
@sickboy this looks great just one minor thing but the rest is awesome.

**Comment by Sonsalt** [comment]
@sickboy External link feedback : https://github.com/SIXNetworks/withSIX-Platform/issues/147
