### ISSUE TITLE
Implement the alternative Steam approach

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX-Platform#108]

**Comment by Sonsalt** [comment]
Initial Test:
Updated to latest alpha and installed extra file.

Client starts
Starting first download
```
An error has occured while trying to 'Action: InstallContent'

An unexpected error has occurred while trying to execute the requested action:
Steam initialization failed. Is Steam running, under the same priviledges?

We've been notified about the problem.

Please make sure you are running the latest version of the software.

If the problem persists, please contact Support: community.withsix.com
```
Steamworks is running: http://staging.withsix.com/p/Starbound/mods/B3AG1AqfeluAbYdrOzlOpA/fixed-banana-based-things-comming-soon-with-admin-and-legit-variations mod tested, worked before. 

----------------------------------

Restarted Alpha with admin rights:

Restarted download

```
Unexpected error has occurred
[Command] An unexpected error has occured: Error: Connection was disconnected before invocation result was received. (Cause: unhandled) We were notified about the problem.
Unexpected error has occurred
[Command] An unexpected error has occured: Error: Connection was disconnected before invocation result was received. (Cause: Unknown) We were notified about the problem.
Action: Unknown error
Error: Connection was disconnected before invocation result was received.
```

Client closes after download (Crash)
https://mega.nz/#!2wJkkDrB!MHF-1SRxntpSmY4KAmU4rYjjU3geXMEEwBTA5UQycu4 (LOGS)

**Comment by sickboy** [comment]
@sonsalt you didn't restart the ALPHA, but a BETA or STABLE client. They don't have the new games.

**Comment by sickboy** [comment]
Fix up in Alpha3.

I've split off additional work to #110

**Comment by Sonsalt** [comment]
@sickboy donload works
