### ISSUE TITLE
Query failed An error has occurred. when looking up author for change

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#118]
Feedback:

- [ ]  Search results not selectable https://gyazo.com/9af68d7680fb72cd8b40deed7dcab91c

I was looking for an Author called Tetet, I do only get Query failed
An error has occurred. 

 use ... via google for login, username is 7a7f21da36394419afb27e831d26360c

"TeTe T" from the google login
or rather, the one where the Nimitz mod is linked against, I think I setup two accounts by mistake

**Comment by sickboy** [comment]
@Sonsalt at this time it seems to work well.
TeT takes a few seconds
TeTe T returns immediately (copy pasted into the field)

**Comment by sickboy** [comment]
@Sonsalt please don't move things to Bug reports without a Comment.

**Comment by Sonsalt** [comment]
@sickboy the search result do appear now, but it is new that you can not click them, so I thought this must be a side-effect of what you did.

**Comment by sickboy** [comment]
@Sonsalt nope, not at all.

**Comment by Sonsalt** [comment]
I did not know, it used to work before.
