### ISSUE TITLE
Ability to repair missing Steam content

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX-Platform#119]
- [x] Auto reinstall mods who's steam content directory is missing
- [x] Manually repair/reinstall mods who's content is incomplete/altered, by running Diagnose action

When a Steam content is manually deleted from the Filesystem, then the content is still considered installed. To reinstall it, one has to re-subscribe to it.

Additionally, when the user deletes subfolders or files, then a Diagnose action should be able to repair it as well.

**Comment by Sonsalt** [comment]
@sickboy how can I test this?

**Comment by sickboy** [comment]
@sonsalt you test this by confirming that it works as advertised.

1. Delete a workshop mod folder
2. Install the Mod
3. Observe no error and that the mod folder is back installed

1. Delete a file inside a workshop mod folder
2. Run Diagnose with that Mod
3. Observe no error and that the deleted file is back

**Comment by sickboy** [comment]
@Sonsalt are you sure this was completely tested?
