### ISSUE TITLE
Implement Gallery

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX-Platform#12]
Using the blueimp library.

- Retrieves the images obtained from the description and all linked apis
- Shows the images in a carousel
- Shows the images in an overview with lightbox support
- Images contain the titles

DONE

- [x] Deduplicate identical images from same location
- [x] Crop images inside Descriptions..

**Comment by sickboy** [comment]
Initial Gallery implemented:

- Retrieves the images obtained from all linked apis
- Shows the images in a carousel
- Shows the images in an overview with lightbox support
- Images contain the titles

(updating todos in the Description of this Issues)

**Comment by Sonsalt** [comment]
the images work nicely, what to to with the known issues, should I put the item back into the backlog now ? @sickboy

**Comment by sickboy** [comment]
@Sonsalt glad to hear, I Think we can split off the remaining two items to a later stadium

**Comment by Sonsalt** [comment]
@sickboy ok, will do
