### ISSUE TITLE
Installation of collection gets stuck after a certain percentageº

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#123]
The collection seems to be stuck downloading after a while, not showing the download speed anymore:

https://gyazo.com/32703837ea4790da8fdfe84dc7ef9d8e (GIF)

Repro:
1. Unsubscribe and delete all Mods from Steamworks http://staging.withsix.com/p/Starbound/collections/Nsf6gpVdnkaOESUq219H8Q/my-first-collection/content
2. Restart Steamworks
3. Start Download
4. Observe error

After Clicking on "install" again the download of the collection completes and the mods can be launched.  https://gyazo.com/07b4a71da4bb34b7b70b1a16ed2a35c7

**Comment by sickboy** [comment]
I've split the Pause error to #125

**Comment by sickboy** [comment]
Might be resolved on next update..

**Comment by Sonsalt** [comment]
QA currently not possible as all mods show Green even if not installed: https://github.com/SIXNetworks/withSIX-Platform/issues/130

**Comment by sickboy** [comment]
No, they only show green when they are installed.

**Comment by Sonsalt** [comment]
@sickboy downloading still gets stuck with the new alpha. The steam Client does stop downloading and within withSIX it says Processing, but no more percentage.... 

I tested by downloading my collection.

**Comment by sickboy** [comment]
@Sonsalt needs detailed reporting.

1. At which mod does it get stuck?
2. What does "Steam client does stop downloading" mean? Is everything in the Queue done? Or is there an item stuck Mid-Download? or At the very start? etc

**Comment by Sonsalt** [comment]
@sickboy 

1. I can not say what mod stopped as the download of the collection in WithSIX and steam does not show these info
2. The Tray icon of steam is green and there is a download bar when steam is downloading something. At the time the webside just showed processing, the client of steam did not download anything anymore

**Comment by sickboy** [comment]
@Sonsalt and 3.? 

Also "Does not download anymore" does not answer my question about mid-download, start-download, finished-download state :)

**Comment by Sonsalt** [comment]
@sickboy 

The Process "Processing" is stuck, there is no actual download happening, it just keeps saying "Processing" without showing the download speed and without actually processing files.

**Comment by Sonsalt** [comment]
@sickboy Update:
1. Deleted All Folders and Unsubscribed from all mods
2. Started Download of my collection
3. Observed this: https://gyazo.com/743b3a4d40e7070254cea72ebc8a1a85
https://gyazo.com/d62e001049ad7cdf37e003e6819a042f

The Collection has 11 mods, in Steam workshop I can see 5 subscribed in My library:

http://staging.withsix.com/p/Starbound/collections/Nsf6gpVdnkaOESUq219H8Q/my-first-collection/content

**Comment by sickboy** [comment]
Thanks.

- We now detect completion from more sources, hopefully addressing the issue
- We've added additional logging to SteamHelper.log (make sure Diagnostics mode is enabled in Sync)
- We now monitor progress reporting. If we don't hear from Steam in the last 60 seconds, we will abort with a Timeout error.

**Comment by sickboy** [comment]
https://github.com/SIXNetworks/withSIX.Desktop/commit/925c669edb50f8480ed059090ea4b3c0338f14c3

**Comment by sickboy** [comment]
@Sonsalt I can't imagine you can confirm this is fixed before testing it 10-50 times, so let's leave it in Testing for now i guess.

**Comment by Sonsalt** [comment]
@sickboy indeed more testing might be good, though I had the issue 100% of the times before and now not anymore, tried twice.
