### ISSUE TITLE
Collections launch every Starbound mod installed

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#124]
When changing a collection to another one with different content, all installed content gets launched. 

Repro:
1. Install Collectione One (http://staging.withsix.com/p/Starbound/collections/Nsf6gpVdnkaOESUq219H8Q/my-first-collection/content)
2. Start Collection One: Observe all mods being lanched properly
3. Install Collection Two http://withsix.com/p/Starbound/collections/tcGNxfZF1kCqCx4BrYaXGQ/my-test-collection/content (Observe collection shows status "Update")
4. Launch Collection Two: Observe Content from collection Two and One is getting launched. 

**Also When launching an empty Playlist all installed mods are loaded.**

**Comment by sickboy** [comment]
This is slightly annoying, it seems sometimes the Steam workshop folders get auto-loaded, and sometimes they don't. This made me switch back and forth between various installation methods.

Ideally we would find a way to enable/disable mods based on configuration instead of renaming files to .bak :)
Anyway, reactivated the Steamdirectory cleaner :D

**Comment by sickboy** [comment]
This is on hold for now as the fix seems to completely disable mod loading... Bit ackward, but will do a full test in the morning :)

**Comment by sickboy** [comment]
Okay, the trick is adding "-noworkshop"

**Comment by sickboy** [comment]
ok apparantly that startup param doesnt exist, and the game decides not to start at all then.
However we now just launch the game without our specialized Steam support, which resolves it also :+1:

**Comment by Sonsalt** [comment]
@sickboy 

Tested with Alpha 5

The game still launches all installed mods, no matter if I select different collections or individual mods.

**Comment by sickboy** [comment]
[Sync diagnostics 131154893116212852.zip](https://github.com/SIXNetworks/withSIX-Platform/files/427696/Sync.diagnostics.131154893116212852.zip)
Attaching works fine test..

**Comment by sickboy** [comment]
@Sonsalt rather strange!

![see dude](https://cloud.githubusercontent.com/assets/42661/17821100/288c48f0-6650-11e6-9351-d723aba620c4.png)

Notice:
- 3 Mods inside Mods directory, of which only 2 active (1 is renamed to .bak)
- Many mods available in the Steam Workshop folder
- Starbound shows just the two active mods
- Starbound shows a greyed out Workshop icon
- Starbound does not show as running within Steam

Starbound is launched over Sync. Alternatively Starbound.exe is manually launched from the Win64 folder, both result in the same behavior.
However when Starbound is launched through Steam, or an older Sync Alpha, then it launches with Workshop support

**Comment by Sonsalt** [comment]
Here are my test results: v1.5.4-alpha5License

1. Checking the Mods within the game I can confirm that all loaded mods have a greyed out Steamworks link. 
2. Zero of the installed mods had a .bak file
3. Even though I loaded just my collection, All mods loaded, even those that were not part of the collection. 
4. Testing with just launching an individual mod also resulted in the same outcome

[Sync diagnostics 131161435201906206.zip](https://github.com/SIXNetworks/withSIX-Platform/files/428140/Sync.diagnostics.131161435201906206.zip)
