### ISSUE TITLE
Pausing a Steamdownload results in error

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX-Platform#125]
When clicking pause, this error appears:

```
An error has occured while trying to 'Action: InstallCollection'
An unexpected error has occurred while trying to execute the requested action:
The process with ID: 15152, did not exit gracefully, CODE: -1
We've been notified about the problem.
Please make sure you are running the latest version of the software.
If the problem persists, please contact Support: community.withsix.com
```

**Comment by Sonsalt** [comment]
Pausing the download now does not cause the error anymore, but the download still continues in Steamworks. Only withSIX shows paused. The download actually completes in Steamworks. 

When unpausing, the download then jumps to finished immediately.

**Comment by sickboy** [comment]
@Sonsalt thats how it currently works yes. The issue in the title is resolved.
