### ISSUE TITLE
Author name search results not clickable

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#128]
Search results not selectable https://gyazo.com/9af68d7680fb72cd8b40deed7dcab91c

**Comment by sickboy** [comment]
@Sonsalt it works fine, but just takes a short while. I know the mouse pointer isn't helpful, but let's keep that for some time when we change things.

**Comment by Sonsalt** [comment]
@sickboy I was clicking on it but nothing happened

**Comment by sickboy** [comment]
@Sonsalt "Nothing happened" is time sensitive. Wait a while.
