### ISSUE TITLE
Starbound mod handling broken

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#130]
It appears that the mod is downloaded into a different folder than it should and existing mods, even when manually uninstalled and unsubscribed still show green.

When opening a mod folder via the interface it opens:  C:\Program Files (x86)\Steam\SteamApps\common\Starbound\win64\.synqmods

while the mod is actually installed to: C:\Program Files (x86)\Steam\SteamApps\workshop\content\211820\745306051

Uninstalling the mod has no effect, the mod remains installed

**Comment by Sonsalt** [comment]
@sickboy downloading mods now cause this error: https://gyazo.com/83446ff628544befbef1c247af2f71bb

**Comment by sickboy** [comment]
@Sonsalt click ignore, and create a new card with the issue.
