### ISSUE TITLE
Support detecting installed (and manually uninstalled) (Steam) content for 3S games

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX-Platform#131]
Feedback:

- [ ] Installed Mod not Detected after restarting Alpha Client

-------------------------------------------------------------
1. Install (a supported) mod over Steam workshop directly
2. Restart client, or save the game's settings, or switch games to another game, and back
3. Observe the Mod was found

and

1. Delete a modfolder
2. Restart client, or save the game's settings, or switch games to another game, and back
3. Observe the Mod no longer shows as Installed

(The experience equals that of the ARMA games. Further desired enhancements may be documented elsewhere)

**Comment by Sonsalt** [comment]
@sickboy 

**Test One:**
1. Opened Steamworks and installed: http://steamcommunity.com/sharedfiles/filedetails/?id=742376260
2. Saved Game Settings (Mod did not show up)
3. Restarted Alpha Client (mod did not show up)

**Test Two:**
1. Deleted Mod folder
2. Restarted Alpha Client
3. Mod was gone from library

**Comment by sickboy** [comment]
@Sonsalt re Test One: When I visit the mod page, it shows orange and "Continue". The point is that we can't confirm the version, until Continue is clicked and we make sure the right version is getting installed.
I guess you were looking at the Home or Mods libraries, these currently do not seem to include mods which are not yet fully completed. Will have a look to add them.

> Is there any way to update in more real time, without restarting the client ?

Sure, make some suggestions when you'd expect these scans to occur, given that:
1. While scanning, the database is locked, and the user cannot perform actions
2. The scanning is relatively fast (3 seconds?)

Alternatively we could have the Steamhelper for a game running while the game itself is not running, this could allow us to monitor for Steam events like "Item installed" or "Item subscribed",
however this would add some complexion to the current implementation.

This needs to be handled in a separate card and scheduled though, the same limitations apply to manually fiddling with A3 mods etc.

A full list of the refresh sources for completeness:
- When saving a game's settings (to catch configured directory changes)
- When switching games, the newly active game will have it's content scanned
- Startup of client (all installed games)
- Every 30 minutes (all installed games)

**Comment by Sonsalt** [comment]
Subscribed mods are now detected but are "uninstalled" they should be "green" as they are already installed

**Comment by sickboy** [comment]
@sonsalt no they should show up as "Incomplete", read the description I gave before.

**Comment by Sonsalt** [comment]
@sickboy indeed, but they show as blue, not yellow.

**Comment by sickboy** [comment]
@Sonsalt that seems quite ackward as they wouldn't show up unless they are in the appropriate state...
Please provide the repro steps, and test under the various conditions, incl client restart.
