### ISSUE TITLE
Collection shows green even though all content was manually deleted

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#134]
1. Delete All modfolders
2. Restart Alpha Client (Observe all mods are gone from library)
3. Collection still shows green

When Diagnosing collection it turns orange (Update available

Expected behavior:
After all mods are deleted, Collection with no installed mods should turn blue.

-------------------------------------

When Clicking on "Update" Steamworks glitches and error message occuers after 10 seconds:
1. https://gyazo.com/decbfdf3cc5616611c5d69b6d87c68a6 (Steamworks installation glitch)
2. Error:

```
An error has occured while trying to 'Action: InstallCollection'

An unexpected error has occurred while trying to execute the requested action:
The process with ID: 32016, did not exit gracefully, CODE: 1

We've been notified about the problem.

Please make sure you are running the latest version of the software.

If the problem persists, please contact Support: community.withsix.com
```
Installation fails

**This could be related to the fact that the deleted content shows as subscribed in Steamworks**

The error does not occeur when I also Unsubscribe to the mods from Steamworks. The collection still shows Green/Orange though.

**Comment by sickboy** [comment]
Possibly related to #127

**Comment by Sonsalt** [comment]
https://gyazo.com/445ade75e78726515f33ada388c6a62d

collection now shows orange when deleting all mods. When clicking Diagnose, it installs them again.

**Comment by sickboy** [comment]
@Sonsalt that's the correct behavior. You didn't uninstall/remove the collection. You removed the content of it, so now it's incomplete/notupdate.

**Comment by Sonsalt** [comment]
Well technically blue would be the correct color as all items within the collections are blue. If a single one would be already half installed then it should take that state.

**Comment by sickboy** [comment]
@Sonsalt yes and no, as it would hide that you Subscribed it sort of :)
Anyway if you want to change it, create a feature request and put it outside the Milestones :)

**Comment by Sonsalt** [comment]
https://github.com/SIXNetworks/withSIX-Platform/issues/139
