### ISSUE TITLE
Deleting collection causes mods to remain in library

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#138]
Most of the mods of the deleted collection remain in the library in various states, some as "continue" some as "installed"

However all items are removed from steam workshop and the mod folders are also empty.

**Comment by sickboy** [comment]
@Sonsalt so you said "Yes" to the question "Uninstall the content of this Collection", 
and then observed this behavior?

**Comment by Sonsalt** [comment]
@sickboy indeed, I have selected yes and observed how the mods were removed from the Steam workshop library and the folders.

**Comment by sickboy** [comment]
@Sonsalt fixed in next build, to recover correct state now, you have to restart the client.
