### ISSUE TITLE
Filter smileys and deduplicate identical images from multiple sources when they have the same name

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#14]
- [x] Filter smileys
- [x] Deduplicate identical images from same sources
- [x] Deduplicate identical images from multiple sources when their image filenames match

**Comment by Sonsalt** [comment]
I did not see smileys before in galleries, regarding multiple images, I think I don't see any doubles either, mostly the smaller images etc are the ones I see.

**Comment by sickboy** [comment]
@Sonsalt perfect, case closed

**Comment by Sonsalt** [comment]
http://staging.withsix.com/p/Arma-3/mods/8Y8Hcpbt6Uu9szC_igutDQ/mffa-more-factions-for-arma3 found dublicate images

**Comment by sickboy** [comment]
@Sonsalt that's nice however they cannot be filtered

**Comment by sickboy** [comment]
@Sonsalt nope, the images come from different sources, have different names, and cannot be deduplicated at this time.
I guess one small tweak we could make is that we should exclude the logo uploaded to withSIX, if there are images in other galleries, as there's a high probability that it will be amongst the galleries.

**Comment by Sonsalt** [comment]
@sickboy copy, thanks for the info

**Comment by Sonsalt** [comment]
@sickboy https://github.com/SIXNetworks/withSIX-Platform/issues/39
