### ISSUE TITLE
Show Comment replies and clicking on Reply takes up to 2min for response

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#141]
https://gyazo.com/63ff9f17b4079662fdb1b707cd6f384e

- [x] "Show Comment Replies" takes a long time to open
- [x] clicking on "Reply" Takes very long until field opens
- [ ] Trying to delete a comment crashes website

**Comment by Sonsalt** [comment]
Clicking on "Reply" still has no effect for a long time. 

https://gyazo.com/619cc8bfa6b2f088f62c543640362330

The Comment window opens after 30 Seconds - 2min

**Comment by Sonsalt** [comment]
@sickboy 

Reply button opens the Reply field instantly now but when replying and clicking on save this error appears

```
Query failed
An error has occurred.
```
The post is stuck in saving

**Comment by Sonsalt** [comment]
Deleting a reply caused massive errors and the entire website to crash:

https://gyazo.com/5156f700ca0f2605c3bee634a59473bc

http://pastebin.com/FueCATHp

Repro:
Add a reply to a comment
Delete the reply
Observe that the comment is saying saving....  then try refresh the page

Query failed
TypeError: Failed to fetch

500 :( Woops.. something went wrong, please try again later!

Unexpected error has occurred
[Command] An unexpected error has occured: TypeError: Failed to fetch (Cause: Unknown) We were notified about the problem.
page load: Unknown error
TypeError: Failed to fetch
page load: Unknown Error
Site down?!

**Comment by sickboy** [comment]
@Sonsalt please don't expand the description beyond the card's title. Create a new one.
