### ISSUE TITLE
External Links enhancements #2

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#147]
- [x] https://gyazo.com/3811018e90b24ef7eeb891eb0c945e70 increas spacing between last row and External links (2 rows space)
- [x] https://gyazo.com/bd4371bd8964409f2845aeb2e763b009 ( combine External links)
( if possible, detect if "mod Homepage" link is BI or Steam and in that case remove...)
- [x] Sort alphabetically

- [ ] de Duplicate links https://gyazo.com/69e5072beb1b4dcc8f31abfb348a2636 http://staging.withsix.com/p/Arma-3/mods/NNbP-3NhDkuTw-sLZmreuQ/pook-sam-pack

**Comment by sickboy** [comment]
> combine external links

lol we already do this for Steam, but I guess not for BI forum, but there must be a formatting difference then, I need the actual link to the mod to look at the links.
