### ISSUE TITLE
Beta not working on some systems

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX-Platform#150]
Seems to be related to Steam Initialization changes.
Evro Malarkey reported this on Discord.

**Comment by sickboy** [comment]
omg, bad code is bad!

1. an infinite loop was created during a refactoring, because the code in question was not obvious (using a bad loop construct). the issue was only triggered on machines which have multiple Steam libraries.
2. static field initializer executing relatively complex code (reading from disk, parsing, processing) made this a pain to debug!

**Comment by Sonsalt** [comment]
@sickboy need info on how to test or who had this issue.

**Comment by sickboy** [comment]
@Sonsalt you need to upgrade your deduction skill, (the art of deduction, Holmes).
The Beta client was not starting, remaining running in the background, if you had a second Steam library (a Steam game installed through Steam client on a secondary drive like D:, creates a Steam Library there)
