### ISSUE TITLE
Internal Server Error message when Adding mods Error 500

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#153]
Request failed
An error has occurred. (500: Internal Server Error)

app.2d6431900964c3ad1986.bundle.js:84 ERROR during request, Request ID: undefined na._write @ app.2d6431900964c3ad1986.bundle.js:84
app.2d6431900964c3ad1986.bundle.js:84 Error: An error has occurred.
(500: Internal Server Error)a._write @ app.2d6431900964c3ad1986.bundle.js:84

I did refresh the page and tried it after 30min again, with the same result:

https://steamcommunity.com/sharedfiles/filedetails/748956823 

---------------------------------------

There is something wrong with my lab group permissions? I cannot delete a group that I just created?
I am getting a 500 internal error on it. SGTGunner - Yesterday at 11:23 PM (DISCORD)

Probably related

**Comment by Sonsalt** [comment]
@sickboy just did another try uploading a mod, error still exists.

**Comment by sickboy** [comment]
@Sonsalt please go through the ModMaster emails and deal with the A3 mods missing updates.

**Comment by Sonsalt** [comment]
@sickboy will do but wow you have no idea how much time this will take
