### ISSUE TITLE
Create Forum/Discord post

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX-Platform#154]

**Comment by sickboy** [comment]
@Sonsalt 's on it?! :)

**Comment by Sonsalt** [comment]
Not sure what this is about, I already created a post on Discord for the new game support and one on Starbound forums, anything else needed ?  @sickboy

**Comment by sickboy** [comment]
@Sonsalt this is about the post on Discord, and I thought you wanted to post it to our community forum aswell, maybe confused with SB/Stellaris/etc forums :)
