### ISSUE TITLE
A3 Description update not working

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#159]
The live description update for A3 mods does not appear to work. It Agregates the links but the Reference is missing.

**Comment by sickboy** [comment]
@Sonsalt not sure what that means, you need to post details, a link to an example, write down expected vs observed.

**Comment by Sonsalt** [comment]
"Information provided as is by Steam, a Valve corporation product" @sickboy this is missing

**Comment by sickboy** [comment]
@Sonsalt then its a description you create

**Comment by Sonsalt** [comment]
@sickboy this might cause an issue, since besides the Author I do 100% of all mods over one account. 

The solution could be that if the description has been imported via "import" button than it does keep updating, from the host pages, only when there has been a manual description it should not.

Any idea?

**Comment by sickboy** [comment]
@Sonsalt it's implemented as requested.
Close this please, and create a new card once we figure out what we want.
I guess we should remove the manual descriptions, if the mod is owned by the bot, and a valid forum/steam etc link is available.
