### ISSUE TITLE
Client always busy

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#161]
The client appears to be in the busy state without any reason (Stable)
[Sync diagnostics 131163619858794652.zip](https://github.com/SIXNetworks/withSIX-Platform/files/430795/Sync.diagnostics.131163619858794652.zip)

**Comment by Sonsalt** [comment]
https://gyazo.com/ee788d27747d53cf8fd42a4474abddc4 the busy stopped but when I start a download it does not register, just a spinner next to the button

**Comment by sickboy** [comment]
@Sonsalt if you refresh the page, do you find an error?

**Comment by Sonsalt** [comment]
https://gyazo.com/23e290ec697ac5ca7f0b74fa493b48d9

This appears immediatly when I do, plus then it appears that the download starts working. 

When Clicking on Install of a mod, the status does not change until F5 of the page

**Comment by sickboy** [comment]
Nice find, events were broken when fixing other client connection related stuff
