### ISSUE TITLE
Auto enable groups module

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX-Platform#169]
- When visiting a Group page
- When visiting a Content page owned by a Group
- When being member of, or owning a Group

https://trello.com/c/a1DleHYi

**Comment by sickboy** [comment]
@Sonsalt Im pretty sure that it works as designed

**Comment by Sonsalt** [comment]
@sickboy I did ask SGt Gunter if this would work and he said no, this i why I moved it back to Bug report

**Comment by sickboy** [comment]
@Sonsalt different expectency vs the specified behavior then, can happen.
I've changed the specification now and implemented it.

**Comment by Sonsalt** [comment]
@sickboy copy, waiting for Sgt.Gunner's response
