### ISSUE TITLE
Selective API sync of Mods, like Collections

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX-Platform#171]
This should heavily reduce the synchronization time, for e.g games with many thousands of mods.
Also allow loading in from external downloads, perhaps with the source included in the ID, and then link it to existing data later when necessary.

Further enhancements documented in #219

**Comment by sickboy** [comment]
I've made a first implementation in SIXNetworks/withSIX.Desktop#37
should be available soon on Alpha.
Still could use some optimization probably.

Current results:

- Use less memory, especially when idle
- Use less disk-space
- Improve time between Install click and start

For future we can consider syncing from dynamic api instead of static.

**Comment by Sonsalt** [comment]
The launched game message appears to be back, related?

**Comment by sickboy** [comment]
@Sonsalt "Game can not be selected error"??
The launched game message never went away from the website. Only as Desktop Notification (windows toast)
