### ISSUE TITLE
Libraries awaiting updates

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX-Platform#18]
- [x] Electron 1.3.0 https://github.com/electron-userland/electron-prebuilt/releases/tag/v1.3.0
 - Needs Edge update
- [x] Edge (for official .NET Core + Node 6.x support) https://github.com/tjanczuk/edge/issues/438 (made a fork)
- [x] Squirrel (for .NET 4.6 requirement) https://github.com/Squirrel/Squirrel.Windows/issues/341 (made custom fork)
- SignalR 2.2.1
 - [x] Backend: https://github.com/SignalR/SignalR/releases/tag/2.2.1
 - [x] Frontend: https://github.com/dfrencham/ms-signalr-client/issues/6
- [x] HTMLSanitizer
 - https://github.com/mganss/HtmlSanitizer/issues/77
- [x] SharpCompress
 - https://github.com/adamhathcock/sharpcompress/issues/152

**Comment by dfrencham** [comment]
Hi @sickboy. I maintain the unofficial ms-signalr-client npm package.

I haven't updated it yet, as the version referenced in the official signal-r repository (https://github.com/SignalR/SignalR/blob/fa864e866bea4737dbd888f993892694f2f6b1a6/src/Microsoft.AspNet.SignalR.Client.JS/jquery.signalR.core.js) is v2.2.1-pre. 

I was going to create a 2.2.1 package when the official repo moves from 2.2.1-pre to 2.2.1. Do you need me to create a 2.2.1-pre version and deploy to npm in the interim ?

**Comment by sickboy** [comment]
@dfrencham hey thanks for getting back to me. Since their release tag is 2.2.1 I think it's an oversight that they left the -pre tag in the JS. I've created a pull request for them: https://github.com/SignalR/SignalR/pull/3748

I think it would be safe to update, but if you prefer perhaps sticking a -pre tag on your release until they confirm, could be the safest bet.

**Comment by dfrencham** [comment]
@sickboy lastest version has been packaged and published to npm.

**Comment by sickboy** [comment]
@dfrencham thanks a bunch!
