### ISSUE TITLE
Optimize Gallery Round Three

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#180]
- [x] https://www.paypal.com/en_US/i/btn/x-click-but21.gif (http://withsix.com/p/Arma-3/mods/hmk1AmXt4xGYTQAVF72WTA/Vcom-AI)
- [x] https://cfl.dropboxstatic.com/static/images/icons/blue_dropbox_glyph-vflOJKOUw.png
- [x] http://store.akamai.steamstatic.com/public/shared/images/header/globalheader_logo.png

Nex:

- [x] https://staticdelivery.nexusmods.com/contents/images/discordbutton.png
- [x] https://staticdelivery.nexusmods.com/contents/Images/icons/icon-log.png
- [x] https://staticdelivery.nexusmods.com/contents/Images/icons/icon-report.png
- [x] https://staticdelivery.nexusmods.com/contents/Images/icons/icon-addimages.png
- [x] https://staticdelivery.nexusmods.com/contents/Images/icons/icon-requiredfiles.png
- [x] https://staticdelivery.nexusmods.com/contents/Images/icons/icon-permissions.png
- [x] https://staticdelivery.nexusmods.com/contents/Images/icons/icon-contact.png
- [x] https://staticdelivery.nexusmods.com/contents/images/premiumbutton.png
- [ ] https://staticdelivery.nexusmods.com/mods/1151/images/8-0-1446847236.jpg
- [ ]

**Comment by Sonsalt** [comment]
@sickboy added some logos found in this mod: http://withsix.com/p/Arma-3/mods/H8zXHQ5vHE2V4mklFvpzrg/PT-17-Stearman?landing=1

Since we will encounter lots of small icons and can not possibly find and blacklist them all we might have to look for a better approach

**Comment by Sonsalt** [comment]
@sickboy 

http://staging.withsix.com/p/Fallout4/mods/hyDVyS_mIU2bzmGJWclMUQ/fallout-4-icon-pack 

The small images are still visible in the gallery

**Comment by sickboy** [comment]
@Sonsalt problem with images vs Images, I made the filter case insensitive now.

**Comment by Sonsalt** [comment]
@sickboy 

http://staging.withsix.com/p/Fallout4/mods/hyDVyS_mIU2bzmGJWclMUQ/fallout-4-icon-pack 

The small images are still visible in the gallery

**Comment by sickboy** [comment]
@Sonsalt its an icon pack! and the images are fine
