### ISSUE TITLE
Add SB community forum DL

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX-Platform#181]
- Take care, often download pak directly (uncompressed)

**Comment by sickboy** [comment]
@Sonsalt As we currently only have Steam SB mods, a select few of SB mods are also linked to the community forums. To test this feature, find one of these mods (Frackin universe?), close steam, rename Program FIles Steam directory to Steam.bak, and then try to install the mod.

In the future we will look into providing options to the user, perhaps first as a priority configuration, (ATM it's: W6 (if uploaded), Steam (if detected), other), and perhaps also as specific option (DL over X, DL over Y).

**Comment by Sonsalt** [comment]
Please configure the game first in the Settings

The requested game appears not installed: Starbound

Error Info: The requested game appears not installed: Starbound

I get this when I change the folder, changing the settings will just reactivate it, any ideas?
