### ISSUE TITLE
500: Internal Server Error when adding mod

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#183]
having the issue again with Request failed
An error has occurred. (500: Internal Server Error) when adding mods. Please fix underlying issue

https://steamcommunity.com/sharedfiles/filedetails/751854728

**Comment by sickboy** [comment]
https://withsix.com/p/Arma-3/mods/S9RshibjH0qHRJQuSCWmUg/Farman-IV
