### ISSUE TITLE
Can't upload new mod avatar

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX-Platform#184]

**Comment by Sonsalt** [comment]
This still fails with this error message:

Failed to upload image.
We were unable to retrieve an upload policy for your image. Please try again later

Tried to upload this file:

**Comment by Sonsalt** [comment]
![nhtsq98](https://cloud.githubusercontent.com/assets/5439794/18020882/ebe28d1c-6bb1-11e6-8368-14d2836dd120.jpg)

**Comment by sickboy** [comment]
@Sonsalt works fine here.
