### ISSUE TITLE
Mod update does not show up on stream and shows previous version

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#185]
http://withsix.com/p/Arma-3/mods/ZsVNy3D3Y0Gi80OwvQscLg/Eurofighter-Typhoon-AWS

The modupdate completed, but still does not show

**Comment by sickboy** [comment]
@Sonsalt show? Show where? It's shown on the detail page, index pages and the stream.

**Comment by Sonsalt** [comment]
@sickboy I linked the page, but now it seems to work.
