### ISSUE TITLE
The requested game appears not installed: Starbound

### ISSUE THREAD

**Issue by sebastin25** [SIXNetworks/withSIX-Platform#201]
So.... how im supposed to configure it? because already try every location i could think about. The client only support steam version?

**Comment by sickboy** [comment]
hi @sebastin25 we currently auto detect the Steam version, and we have access to all the mods on Steam.
When authors upload mods also to our platform, then you should be able to use those too.
We're looking at supporting mods hosted on the chuckelfish forums too..

In any case you'd configure the game path to the root of the game folder, e.g: C:\Games\Starbound
(the folder would then contain these sub folders, we auto-pick the right executable)
- win32\starbound.exe
- win64\starbound.exe

**Comment by sebastin25** [comment]
GoG version:
C:\GOG Games\Starbound
- win32\starbound.exe
- win64\starbound.exe

looks like the executables are in the same location

Thats the error im having when i select C:\GOG Games\Starbound as the game directory
http://imgur.com/a/LDMhf

**Comment by sickboy** [comment]
@sebastin25 got it, will address this issue shortly! 
As to the content availability, we're putting some dot's on the i atm with regards to non-steam mod content, might go into the BETA in the next 1-2 days.

**Comment by sickboy** [comment]
@sebastin25 All issues should be adddressed in the just released v1.6.1-beta2 (to install: download the Sync BETA from: http://withsix.com/download, close the STABLE client, and then install).

Full changelog available at http://withsix.com/update

**Comment by sebastin25** [comment]
Now is working as intended, ty for the help

**Comment by sickboy** [comment]
@sebastin25 sure thing, thanks for hanging in there!
