### ISSUE TITLE
Update of collection fails

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#202]
- [ ]  Collection shows wrong error when updating and STEAM is not running
- [ ]  Steam does not autostart 
- [ ]  When updating collection and steam is running, update fails but finishes on steam
- [ ]  When installing update after steam workshop completed, update completes, but playlist and content pages still show update available

http://withsix.com/p/Starbound/collections/IdV8m3vXX0O1esCzTRGYzg/better-universe
```
`An error has occured while trying to 'Action: InstallContents'

An unexpected error has occurred while trying to execute the requested action:
An item with the same key has already been added.

We've been notified about the problem.

Please make sure you are running the latest version of the software.

If the problem persists, please contact Support: community.withsix.com
```

`

The reason is that steamworks is not launched. But there is also no info that this is the problem, nor does it launch automatically.

After Starting Steam, the download continues. in Steam but still says failed in the withSIX client. 
[Sync diagnostics 131170790602346811.zip](https://github.com/SIXNetworks/withSIX-Platform/files/446211/Sync.diagnostics.131170790602346811.zip)

Clicking on Update, after the download has been completed on Steam workshop, shows the client "installing" even though the Steam client is not active. After a while the collection shows installed in the tray but the content page status still says "update" 

https://gyazo.com/a87de3ff51c7aef836e3255cfcae1792

**Comment by sickboy** [comment]
@Sonsalt the error has nothing to do with Steamworks not launched. It would launch at a later stage.

**Comment by Sonsalt** [comment]
@sickboy ok, I hope my info helps you tracking down the issues :)
