### ISSUE TITLE
To learn more, follow this guide. (Update docs and link)

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#204]
Currently we are linking to our docs for claiming, we should add our youtube video to it, that shows how to update mods. This should be on the top of the guide. 

https://www.youtube.com/watch?v=2To1Yd4Adv0&index=2&list=PLdN1badSc6BrjiImodcojI4ZwvjBTj1zE

**Comment by sickboy** [comment]
@Sonsalt go ahead and [edit it in](https://github.com/SIXNetworks/withsix-docs/edit/master/docs/general/get_started_publishing.md)
