### ISSUE TITLE
Inform the user in at least a basic way about the external download process

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX-Platform#205]
- [ ] Don't set state "continue" if download has not been actually initiated. 
- [x] Update Text

Add dialog upon external content to install:

**Title:** This content is hosted externally. 

**TEXT**
To start the automatic installation, initiate the download on the external website. 

Click CONTINUE to open the download page and follow the instructions until the download starts. 
_(Login might be required)_

                                                              (CANCEL) (CONTINUE)

------------------------------
Ref #201 
Related: #228

**Comment by Sonsalt** [comment]
Currently blocked as Download fails: 

Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
app.0aa84caaf7ce9af4e942.bundle.js:1 Array[2]a._write @ app.0aa84caaf7ce9af4e942.bundle.js:1
app.0aa84caaf7ce9af4e942.bundle.js:1 Error: Error: simple-extended-character-creation-mod-now-even-easier.218 source .pak not found! You might try Diagnosinga._write @ app.0aa84caaf7ce9af4e942.bundle.js:1
app.0aa84caaf7ce9af4e942.bundle.js:72 [Command] An unexpected error has occured: Error: simple-extended-character-creation-mod-now-even-easier.218 source .pak not found! You might try Diagnosing (Cause: Unknown)t.GlobalErrorHandler.GlobalErrorHandler.tryErrorLog @ app.0aa84caaf7ce9af4e942.bundle.js:72
app.0aa84caaf7ce9af4e942.bundle.js:1 Error: [Command] An unexpected error has occured: Error: simple-extended-character-creation-mod-now-even-easier.218 source .pak not found! You might try Diagnosing (Cause: Unknown)
We were notified about the problem.

**Comment by sickboy** [comment]
@Sonsalt no it's not blocked, you already echod the dialog to me.

**Comment by sickboy** [comment]
@Sonsalt 
>  Don't set state "continue" if download has not been actually initiated.
That's going to get complicated. Please extract.

**Comment by sickboy** [comment]
@Sonsalt are you aware and took into account that we can download multiple content, from multiple sources, e.g:
- 2 mods from SB forums
- 1 mod form Steam
- 4 mods from our own network

**Comment by sickboy** [comment]
@Sonsalt for next alpha I have actually also covered your request not to put items into Continue mode when the download is not initiated on the external site.

**Comment by Sonsalt** [comment]
@sickboy copy, will test, the continue button is currently white, by design or error ?

https://gyazo.com/28a2d93670484f623b002bdf4bc9ae26

**Comment by sickboy** [comment]
@Sonsalt we don't have a design for Continue buttons, it is the first time we use one,
how do you expect it to look like?

**Comment by Sonsalt** [comment]
@sickboy usually we use green,
