### ISSUE TITLE
Investigate and reduce "Only one action allowed per game" error

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX-Platform#210]
Related to #212 and #171

**Comment by sickboy** [comment]
This should be quite reduced due to #171, perhaps even to an acceptable level.

**Comment by sickboy** [comment]
The main cause for "Only one action supported per game" upon performing an action,
is because another browser/tab has touched another game in the meantime.
This issue has now been resolved. We no longer act (towards the client) as if the user switched games upon performing an action.

**Comment by Sonsalt** [comment]
Feedback:

Error message occurred and opened several times at once over another: https://gyazo.com/d44566d91071283e82c134b3b389b2a6 

Repro:
1. Open STARBOUND steam page
2. Select http://withsix.com/p/Starbound/mods/aaKH4U0hslOmflFPWTe2Dw/creative-mode---complete-control-over-your-experience and click on Install
3. Start Sync Alpha
4. Retry, clicking on "INSTALL"
5. Observer, first Warning message appearing and 30 seconds later Error message appearing

(The error message appears automatically after a few seconds, do not click on anything else)

**Comment by sickboy** [comment]
@Sonsalt this is a related issue but is a special case, and something I want to handle separately, at lower priority. Please extract.
