### ISSUE TITLE
Add and test drive basic launch as server support

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX-Platform#222]
Initial target: Starbound and ARMA-3.

- [x] Launch playlist as server (Add to the Playlist dropdown menu, if the Playlist is launchable (Installed))
- [x] Launch collection as server (Add to the Collection dropdown menu, if the Collection is launchable (Installed)

(this excludes any additional configuration/dialogs etc, merely the basis for launching as server)

**Comment by Sonsalt** [comment]
@sickboy It appears to work but I have no idea how to test the user side and check if the mods are loading.

**Comment by sickboy** [comment]
@Sonsalt also added distinction now between Launch as Server vs Launch as Dedicated Server
