### ISSUE TITLE
An error has occured while trying to 'Action: SelectGame'

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#224]
https://gyazo.com/33aa8cb9020e520b9b083cebfc69a5cf

Happens When:

1. Idle and performing any action after a while (Changing page....)
2. Changing selected Game
3. Clicking on Stream button within the same game while being on mods view

**Comment by sickboy** [comment]
Alpha5 fixes this.

**Comment by sickboy** [comment]
There's another source of the same error, documented in #225, on the way to be fixed.

**Comment by sickboy** [comment]
@Sonsalt the issue is fixed in #225
