### ISSUE TITLE
v3 api for arma3 includes arma2 mods, it shouldn't, as they are fetched separately

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX-Platform#225]

**Comment by sickboy** [comment]
Should be sorted on next api sync, perhaps in half an hour or so

**Comment by Sonsalt** [comment]
@sickboy how do I test this?

**Comment by sickboy** [comment]
@Sonsalt you had an error when switching to ARMA3, you should no longer get an error.
