### ISSUE TITLE
Mediafire Installation Error Starbound (User Report)

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#226]
Mod: http://withsix.com/p/Starbound/mods/3RY66sVKGVuwf-_BIu9q9g/Kirhos-Discontinued
Forum Report: http://community.playstarbound.com/threads/starbound-withsix.123043/#post-3014611

Report:
A user has reported, that he was unable to install Kirhos mod. The mod is hosted externally on Mediafire and linked from the Starbound forum.

Repro:
- Downloaded via Sync Alpha v5
- Installation fails, unknown format (kirhos.modpak)

Findings: Mod file type appears to be unknown

**Comment by Sonsalt** [comment]
The error message is gone, but the mod does not show up ingame. 
[Sync diagnostics 131176443851224064.zip](https://github.com/SIXNetworks/withSIX-Platform/files/456877/Sync.diagnostics.131176443851224064.zip)

**Comment by sickboy** [comment]
@Sonsalt are .modpak mods supposed to show up?

**Comment by Sonsalt** [comment]
@sickboy that I don't know. .... will investigate

**Comment by Sonsalt** [comment]
http://community.playstarbound.com/threads/how-to-install-modpak.102664/ 

Well According to this it should be enough to place it into the "mods" folder

**Comment by sickboy** [comment]
@Sonsalt it's an old post, and you should read the bottom: http://community.playstarbound.com/threads/how-to-install-modpak.102664/

We already install them as .pak now.
