### ISSUE TITLE
Installation failed Unexpected Error (Starbound)

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#227]
Error Message:
Unexpected error has occurred
[Command] An unexpected error has occured: Error: 758745406 source not found! You might try Diagnosing (Cause: Unknown) We were notified about the problem.
Action: Unknown error
Error: 758745406 source not found! You might try Diagnosing

**Repro:**
1. Start Sync Alpha and steam
2. Open Starboun Stream
3. Select http://withsix.com/p/Starbound/mods/7GpPxQ0RfFiFbpu5Xh6RYg/trap-crafting-station
4. Open Mod page
5. Click on Download

6. it completes when clicking "continue"

**Comment by sickboy** [comment]
It seems that sometimes Steam isn't fast enough to put the download files in place... we might have to add some sort of artificial delay, or somehow find a away how we can detect Steam being really done.

It might be that we do get the signal at the right time, but that our workarounds prematurely detect the completion state.. That actually sounds logical. Will have a look :)
