### ISSUE TITLE
Performance issues of Sync features on the site

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#23]
We have reports of users, suffering from performance issues using the Site (Sync related functionality)

- [ ] Opening of PL and QL stutters 
- [ ] Showing content for PL and QL takes up to 30 seconds upon first loading

**Comment by sickboy** [comment]
@Sonsalt i've split the unrelated issue to https://github.com/SIXNetworks/withSIX-Platform/issues/24
