### ISSUE TITLE
Save changes to a Mod which has many Dependents and or Collections can take a long time

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX-Platform#24]
Saving Changes to Links etc in Editor view for content takes up to 2 minutes

Repro slow Description change:

1. open: http://withsix.com/p/Arma-3/mods/3PMzKSEIJ06qFm1INU6XHg/RHS-United-States-Armed-Forces
2. Change Description
3. Click on Save,

http://withsix.com/p/Arma-3/mods/3PMzKSEIJ06qFm1INU6XHg/RHS-United-States-Armed-Forces
https://gyazo.com/0cd5aff001f2cb7f28b811b040e66738 this status shows for up to 5min

**Comment by sickboy** [comment]
Yep.. we were eager-loading all Dependents (mods who depend on this mod, not to be confused with Dependencies), and Collections that contain this mod.
RHS has 3.2k collections :)

**Comment by Sonsalt** [comment]
Oh yes, that, indeed the related tab :dancers:
