### ISSUE TITLE
Support imgur (and similar services) galleries

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX-Platform#28]
e.g:
- http://imgur.com/a/J0uca
- http://imgur.com/gallery/xHLTY

**Comment by Sonsalt** [comment]
http://staging.withsix.com/p/Arma-3/mods/YpimoO5J4xG4UwAVF72WTA/rh-m4-m16-pack (Working)

**Comment by sickboy** [comment]
Moar :) https://staging.withsix.com/p/Arma-3/mods/COlKJv4s5BGUQAAVF72WTA/aggressors-weapon-replacement
