### ISSUE TITLE
Update/Changelog page can cause 403 when GH API rate limit reached

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX-Platform#29]

**Comment by sickboy** [comment]
@Sonsalt hard to test unless you ran into the ratelimit, however you can search for 'usercontent' in the Network tab of the console, and find that the CHANGELOG.md is gathered from there, and that the changelog is still rendered ;-)

**Comment by Sonsalt** [comment]
how can I emulate the situation, ok, guess this is just done :)
