### ISSUE TITLE
Download of Mods via API control

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#3]
The User should be able to use our Web interface to initiate and observer the Download progress. 

- [x]  Detect if User has Steam account and game installed
- [x]  Start Download by using withSIX "Install" function (content page, stream, QL, Playlist)
- [x]  Start Download of multiple mods that have been combined (PL and Collection)
- [x]  Show Download progress for downloading mods (Download speed, progress, items)
- [x]  Show Status of mods for user (Mod installed, not installed, out of date)

Existing Sync Functions:

- [x] Uninstall mods
- [x] Diagnose
- [x] Open Installation folder

**Comment by Sonsalt** [comment]
Can't wait for this feature :D

**Comment by sickboy** [comment]
@Sonsalt the wait is over!
Some limitations documented in #60

**Comment by Sonsalt** [comment]
Initial Download test was successful, as there are still unchecked items I put this back to Sprint backlog

**Comment by sickboy** [comment]
@Sonsalt this was tested with Alpha5? Since pausing should've been implemented for it etc.

**Comment by Sonsalt** [comment]
@sickboy 
The issue is still persists.

I have tested again with the latest alpha 7 
1. when downloading it goes to Processing until done
2. Pausing causes infinite loop. 

http://staging.withsix.com/p/Starbound/mods/GNktX8zU8Fu_uQHEdAUrxg/alien-music-replacer-sountrack-needed

**Comment by sickboy** [comment]
Awaits progress on #83

**Comment by sickboy** [comment]
Extracted feedback to #87
