### ISSUE TITLE
Bugs with Playlist

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#30]
- [ ] Loading Collection into PL does not load content:  (Not every time) https://gyazo.com/3c4c3cb6e2d4450627ea60b342abbaae
- [x] Hover over button on Banner does not fit 100% lower part 1 Pixel too high
- [x]  https://gyazo.com/223746eccbb3979e69f88eaf2c221664 (White bar below search field)
- [x]  https://gyazo.com/f4b42cf6ae541dc3cce488a4a3001e99 (White dots below long col. Name)
- [x] https://gyazo.com/f6d73182319840ab7425f4b80db5571f long modnames cause hover over issues

**Comment by sickboy** [comment]
> Loading Collection into PL does not load content: (Not every time) https://gyazo.com/3c4c3cb6e2d4450627ea60b342abbaae

can't repro
