### ISSUE TITLE
Aggregate links, just like images

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX-Platform#32]
- Social
 - Facebook
 - Twitter
 - Googleplus
 - Github
 - Steam workshop page
 - BIF
 - Armaholic
- Galleries
 - imgur
- "Other" links

(extend list as we go along)

**Comment by Sonsalt** [comment]
Very interesting concept.

**Comment by sickboy** [comment]
I've extracted facebook, twitter, google plus, the usual forum sources, github etc.
They're just shown as text links under the External Links section.

Awaits input from @Sonsalt and @ParaGraphicL for Where and How to display etc.

**Comment by Sonsalt** [comment]
@sickboy how to best test this?

**Comment by sickboy** [comment]
@Sonsalt  the display part of this isn't finished yet, currently we just grab the links and show them at the External links section, we should process them properly, with logos, categorization etc.
We can also add a Support the Author section, for links to paypal/patreon/wmtransfer etc.

We should add that in a new card.
