### ISSUE TITLE
PL and QL performance issues

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#34]
Feedback: 2

- [x]  Removing mod from collection, saving then loading another collection and loading again restores mod... https://gyazo.com/fb5628916626ee610c1306887c49aa9a (MOD not deleted)
- [x] Collection search in playlist info not updated on changes

Feedback:

- [x]  Error In SyncUI Beta with opening QL and PL https://gyazo.com/0b7f354f503201e37b3854bfe057d72d
- [x]  Loading Saved copy of other collection after cleaning PL causes Error (https://gyazo.com/72c12cd055d78a53a84c23b62632a429)
**Happens also with any other collection change**

Repro:
 1. Save copy of : http://withsix.com/p/Arma-3/collections/jjIZkVh-IkmYBwxy_BDI8w/Tactical-Battlefield-official-TacBF-RHS-AiATP-TFR-CBA-JSRS
 2. Remove "Task force Radio" using PL
 3. Save changes
 4. "Clear" playlist
 5. Load Copy of collection -> observe error
(Unexpected error has occurred
[Command] An unexpected error has occured: TypeError: Cannot read property 'dependencies' of undefined (Cause: Unknown) We were notified about the problem.
Action: Unknown error
TypeError: Cannot read property 'dependencies' of undefined)

Issues:
- [x] Opening the PL, sometimes takes up to 30 seconds to load 
- [x] Switching between QL and PL sometimes takes up to 60 Seconds
- [x]  Opening empty PL sometimes takes several seconds: https://gyazo.com/f5d86f977a1db3c78eeebba3c053570b

**Comment by sickboy** [comment]
dup of #23

**Comment by Sonsalt** [comment]
@sickboy I could not find the other to add the info needed, so I created this one. We can close the other.

**Comment by sickboy** [comment]
@Sonsalt 
> Saving PL after selecting Version for mod when Collections are added does not save. Clicking save causes 2min loading animation, Save button remains green afterwards. Clicking again has no effect.

still can't repro this

**Comment by sickboy** [comment]
@Sonsalt Second layer of performance issues is almost live..

**Comment by sickboy** [comment]
@Sonsalt server-connected-collections missing wouldn't make sense, please be explicit, are they subscribed collections, owned collections? Either one or both of these must be missing.

**Comment by sickboy** [comment]
Renamed this card and extracted issues to #49

**Comment by Sonsalt** [comment]
RE Tier1 collections: They are subscribed collections and I can see them in QL, but not in PL

**Comment by Sonsalt** [comment]
@sickboy Sync UI still laggy, not refreshing I assume

**Comment by sickboy** [comment]
@Sonsalt for refresh issues go #48
