### ISSUE TITLE
Launching Game with selected mods

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#4]
This is very crucial, we need to be able to not only remotely start the game but also with the right modest. Since every game has it's own way to do that, this requires probably the most custom adjustments. 

- [x]  Start Selected games via Interface
- [x]  Launch game with chosen mods

**Comment by sickboy** [comment]
For Starbound, currently all mods which are installed will be activated.
For Stellaris, currently all mods will be available for selection inside the official launcher.
Will have to devise the final planning on how to fill this in with our Playlists etc :)

**Comment by sickboy** [comment]
Some limitations documented in #60

**Comment by Sonsalt** [comment]
@sickboy 

I Did try to launch the mods, but the game did not launch.

Repro:
1. Downloaded a collection of mods
2. Clicked on Launch button after DL was completed
3. Waited for 5min, After about 3min a windows notification appears "... launched"
Then it switched back to idle

**Comment by sickboy** [comment]
@Sonsalt was an issue on your system

**Comment by Sonsalt** [comment]
@sickboy  looks good, Games launch

**Comment by sickboy** [comment]
For Starbound:
- We now copy the .pak to the mods dir
- We rename to .bak for mods that shouldn't be enabled

For Stellaris:
- We now edit the settings.txt to enable/disable mods accordingly

For Skyrim:
- We still need to explore how enabling mods goes - I would keep this for a bit later. We can also investigate how to know if SKSE needs to be installed/enabled etc too.

**Comment by Sonsalt** [comment]
@sickboy Stellaris works like a charm, very well done. 

Should I move the ticket into done and create a new one for Skyrim ?

**Comment by sickboy** [comment]
@Sonsalt oki

**Comment by sickboy** [comment]
@Sonsalt also implemented for Skyrim in the meantime ;)

**Comment by Sonsalt** [comment]
@sickboy will check skyrim once I have it downloaded
