### ISSUE TITLE
Support BI Forums classical VB urls vs modern IPB urls as Publishers properly

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX-Platform#41]
We've accidentally stored classical BI forum urls as if they were modern urls, and therefore they don't match up. Classical urls need to be handled differently.

**Comment by sickboy** [comment]
@Sonsalt to test you need to find a mod that has a classic bi forums url, 
and then confirm that the "Bi forums info" loads, and doesn't cause an error :)

**Comment by Sonsalt** [comment]
@sickboy The error message is now not showing anymore, but the description loaded is missing major elements or often is empty. The Item below is loading:

http://staging.withsix.com/p/Arma-3/mods/1O3V7Y9o3xGYF1RSABEhmA/sti-uh-60l
http://staging.withsix.com/p/Arma-3/mods/eFD7wJVo3xGYF1RSABEhmA/glt-airweapons-replacement-pack

**Comment by sickboy** [comment]
@Sonsalt not sure what major elements means or often empty. But it has nothing to do with this card.
