### ISSUE TITLE
syncws:// url handler should launch latest version not specific version

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX-Platform#42]
If the user updates the client, but doesnt restart it from the desktop shortcut,
but it's auto started from website (url handler), then the user will start the old version and will keep an "Updating to x" version message indefinitely.

**Comment by Sonsalt** [comment]
@sickboy to test I will have to wait for a new client version.

**Comment by sickboy** [comment]
@Sonsalt woops, forgot to hit the button it seems :)
