### ISSUE TITLE
Videos in gallery, improvements and fixes

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#43]
- [x] Video should start playing on click, not require a second click
- [x] Images of videos in Thumbnaisl are streched
- [x] Play Overlay on Thumbnail looks stretched 
- [x] Remove Grey overlay box on play button (Check attached link for detail)
- [x] Video Thumbnails appearing in the carousel are very small
- [x] Clicking on a video Thumbnail brings up a small image of the video
- [ ] Clicking on Play does go Full-screen, it should appear like an image, center and not full screen (this allows the X button on the top to close the video. 

If the overlay becomes an issue, we can go this route: 
https://html5box.com/html5gallery/ (Load video into main window)

**Comment by sickboy** [comment]
@Sonsalt great list! We need to flesh out these items before they're actionable

**Comment by Sonsalt** [comment]
during our call

**Comment by sickboy** [comment]
@Sonsalt 
> Clicking on Play does go Full-screen, it should appear like an image, center and not full screen (this allows the X button on the top to close the video.

It's not configurable, it would require to hack, and I believe it's not really worth it. I think the experience is fine. You can use the Carousel if you want inline play, you can use the lightbox if you want full screen play. Pausing the video by clicking anywhere, or on the pause button, or pressing escape, closes it.
