### ISSUE TITLE
Improve Gallery Images

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#45]
**Stretching of images:**
We could increase the size of images by 50% if they don't fully fit. Steamworks apparently does this. The importance is that we keep the ratio the same: http://staging.withsix.com/p/Starbound/mods/9tDeupIEilaD-O74wz5zzQ/slightly-better-wall-jump:
https://steamcommunity.com/sharedfiles/filedetails/732815457

**Blacklist**
- [x] Don't load Banner image into Gallery
- [ ] Don't load images of imported Forum post into Gallery if post is showing. 

**Gallery Whitelist**
- [x]  Steamworks Gallery Images
- [x]  Imagur Image gallery
- [ ]  http://www.hostingpics.net/

... to be expanded

**General**
- [ ] Don't load broken links (http://jsrs-studios.com/images/sb7573y7.png) in http://staging.withsix.com/p/Arma-3/mods/csVAvCOIJUSoCnjMXYq88A/xeno---taru-pod-mod
- [ ] Steamworks DL image (http://i.imgur.com/dDprpzF.png, http://i.imgur.com/1X9nEMo.jpg)
- [ ] If possible min size XY ( This would already take care of most of the link images, like DB, Mega etc)

**BI Forum Image import Blacklist**
- [x]  http://button.moddb.com/ (http://button.moddb.com/download/medium/45522.png)
- [x] withSIX Banner
- [x] BI License: (https://www.bistudio.com/assets/img/licenses/APL-SA.png)
- [x] AH (http://www.armaholic.com/datas/users/news_download_a3_3.png)
- [x] AH Requirements: http://www.armaholic.com/skins/Blaster07/img/required_addons.png
- [x] Paypal: https://www.paypalobjects.com/fr_FR/FR/i/btn/btn_donateCC_LG.gif
- [x] CC images (https://i.creativecommons.org/l/by-nc-nd/4.0/88x31.png)

**Gallery Loading Priority (DEDUPLICATION effort)**
- [ ] IF Steamworks gallery is available, don't load AH
- [ ] IF Imagur Gallery is available, don't load BI Forum images (First post)

**Comment by sickboy** [comment]
> Don't load images of imported Forum post into Gallery if post is showing.

Why not? Also iirc we would just make the images in the post smaller.

**Comment by Sonsalt** [comment]
@sickboy 

I did check 40 mods and the general output is quite good. Only issue remaining is very tiny images. These are mostly icons, blacklisting each one is hard as they come in all shapes and links. 

**Examples:**
http://staging.withsix.com/p/Arma-3/mods/etoMALy4W0ih7UzPe8PYRQ/ace3---a-collaborative-merger-between-agm-cse-and-ace
http://staging.withsix.com/p/Arma-3/mods/fg86s5Nw4xGiHQAVF72WTA/iron-front-in-arma-3

Besides this I think it is more than good enough for the initial release. 

licenseicon to blacklist
- [ ] https://www.bistudio.com/license-icons/small/APL-SA.png

**Comment by sickboy** [comment]
@Sonsalt fixed paypal, added the alternative bi license url, and the wmtransfer.com.

I guess we can pick up the donation links+logso, and perhaps even the license links+logos, and treat them as Interesting links. Categorize and display them appropriately.

Please extract everything that we still want implemented some day, and then I guess this can be moved to done :)

**Comment by Sonsalt** [comment]
@sickboy copy will do, good work.

**Comment by sickboy** [comment]
I've extracted the donation and license links to interesting links :) https://github.com/SIXNetworks/withSIX-Platform/issues/32#issuecomment-237583927
