### ISSUE TITLE
Create Section pages for new Game

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#5]
Like for every existing game, we need to copy and paste all game related Sections:

- [x] Game Stream with updates and new mods 
- [x] Content pages 
- [x]  Filter Page for mods and collections with search
- [x]  Search functions for mods 
- [x]  Library and home area

**Comment by sickboy** [comment]
The stream and search would only be possible once we synchronize the mod info, however for a starters test we will just link in the info directly from API so we can test it properly, while we finish the synchronization for Search and Stream.
