### ISSUE TITLE
Canceling Download of collection causes Error messages

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#52]
```
Unexpected error has occurred
[Command] An unexpected error has occured: Error: Connection was disconnected before invocation result was received. (Cause: unhandled) We were notified about the problem.
Unexpected error has occurred
[Command] An unexpected error has occured: Error: Connection was disconnected before invocation result was received. (Cause: Unknown) We were notified about the problem.
Action: Unknown error
Error: Connection was disconnected before invocation result was received.
```

These error occeur when pausing the download of a collection. Using latest beta 1.4.0.5

**Comment by sickboy** [comment]
@Sonsalt this is a duplicate. The answer back then was that I can't reproduce it.
Also it seems the error is the same as when deleting collections.

**Comment by sickboy** [comment]
@Sonsalt could it just be that the client silently crashes afterwards or so? And perhaps silently restarts too.. Please monitor.

**Comment by Sonsalt** [comment]
@sickboy QA not possible due to: https://gyazo.com/a0a862dfcb507058c18303e46a94b8c0

**Comment by sickboy** [comment]
@Sonsalt I have no idea why QA wouldn't be possible because of a Youtube video upload
