### ISSUE TITLE
Upgrade Aurelia to 1.0.0!

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX-Platform#58]
- [x] Fix webpack plugin
- [x] Update webpack configuration
- [x] Reapply CSSResource for SCSS
- [x] Disable closing tabs when clicking on the bars

**Comment by Sonsalt** [comment]
@sickboy what is it I should look out for?

**Comment by sickboy** [comment]
@Sonsalt does the site work, is the main question of all :)

**Comment by Sonsalt** [comment]
@sickboy lol, looks like it is working, was just wondering if I have to check the libraries and their functions
