### ISSUE TITLE
Statistics and Tags

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#6]
In order to allow users to find the right mod, we have to add Tags and statistics. 

Local Statistics:
- [x]  Installs

Steamworks Tags
- [x]  Finite List
- [ ]  Show incompatible Items 

**The Problem here is, if we fully use the Steam Statistics and Tags, we really might get too close to just be a Steamworks mirror!** 

It would make sense to generate a new "meta" score that combines the statistics of several download platforms to show a total score. On a basic level this could just be the Total downloads. On an advanced level it can take other statistics, such as likes into account.

**Comment by sickboy** [comment]
@sonsalt this card has no actionable items, just a bunch of thoughts and wishes, and maybes.
We'll have to work on it to become actionable..

**Comment by Sonsalt** [comment]
@sickboy 
Local Download Statistics do not work. I installed several mods but it keeps saying 0 installs

**Comment by sickboy** [comment]
Installs fixed in 1.5.0-alpha9, Install vs Updates fixed in 1.5.1.alpha0
