### ISSUE TITLE
Migrate legacy categories to tags

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX-Platform#62]

**Comment by sickboy** [comment]
Categories copied to Tags, still need to finalize the migration (in the maintenance window tomorrow)

**Comment by sickboy** [comment]
@Sonsalt for testing; Do the tags show for A3/other games?
Can you add/remove tags for A3?

**Comment by Sonsalt** [comment]
@sickboy 
I can add remove tags for A3, they are also persistent.
