### ISSUE TITLE
Drop 'Name' from v3 API

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX-Platform#63]
If we provide the action names during content calls, then we should no longer need the Name field at all, and save a bunch more on Client API syncs...

It is being used for e.g displaying the name in ActionNotifications, or ContentPaths -> Name.Sluggify(). Which in turn is used for providing Href to Action notifications

Related to #171 and #210

TODO

- [ ] Remove the Name field from the API once we go public
- [ ] Evaluate if we still need Names for local collections, e.g for Recent (Playlist XX) or imported from PwS (really just need to upgrade those to online anyway..)
- [ ] If neccessary we could still consider Names synced from a dynamic api later #171

**Comment by sickboy** [comment]
An initial implementation is being test driven in the dev labs.
The idea is that the website provides the client with Name information (and in future also the link to the content). When the content is shown in the web UI, the web will enhance the information with the full (and latest updated) name, just like all the other information is already.

For the future we can investigate how we will deal with caching info e.g for offline use.

The immediate result is:
- Less memory usage
- Less disk usage
- Faster actions
- Eventually when we update the API, we will also send a lot less data over the wire on each API sync etc.

**Comment by Sonsalt** [comment]
@sickboy I need informations for QA, hat to look for.

**Comment by sickboy** [comment]
@Sonsalt does the website and client notifications still display the name of the mod/collection?
Does launching, installing or updating of content still work?
Does it indeed no longer show "One moment..." when installing/updating/launching individual mods?
