### ISSUE TITLE
Use .NET4.6 requirement in Setup.exe

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX-Platform#67]
So that Win7 users don't first need to install 4.5 (becuase of Setup) and then 4.6 (because of starting the client).
And so that Win8 users don't need to do the manual 4.6 download+install (because of starting the client).

https://github.com/sickboy/windows-installer

**Comment by sickboy** [comment]
@Sonsalt I tested this myself on Windows 7, 8.1 and 10 vm's.

**Comment by Sonsalt** [comment]
@sickboy ok, since this is difficult for me to test I will move it to done then ?
