### ISSUE TITLE
Implement Steamwork Stats

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#75]
**Possible Steamworks Statistics:**
- [ ] Most popular on Steamworks (Today, One Week, Three Weeks, Three months, Six months, One year, all time)

Implementation
- [ ]  Use "Most popular" as Main Statistic (if possible with the time filter)
- [ ]  Default Sorting by Subscribers in Mod filter
- [ ]  Add other Steamworks Statistics to Filter options

**Comment by sickboy** [comment]
So far I can get Subscribers, Favorited, Followers, +LifeTime variants. The LT variants are the ones of interest right now I think.

**Comment by sickboy** [comment]
@Sonsalt collecting, however we need to figure out how to deal with the following details:
- Do we change the Order dropdown? Or do we just internally map "Installs" to "Subscribers"
- Do we leave our "Installs" stats on the Detail pages and cards, or do we replace it with "Subscribers"?

**Comment by Sonsalt** [comment]
@sickboy if we show "Total subscribers" we should call it installs. Since "Subscribers" means the ones that are active. So we keep installs.
