### ISSUE TITLE
SIXRep #0004 

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#84]
- [x] Prepare Template
- [ ] Prepare Text @sickboy 
- [x] Prepare Text @Sonsalt
- [x] Prepare GIFs
- [x] Prepae Banner 
- [x] Post Blog
- [ ] Post FB
- [ ] Post Twitter

http://withsix.com/me/blog/sixrep-0004-collectioninception

**Comment by sickboy** [comment]
@Sonsalt the part about servers and custom repos is untrue.

First of all, if a collection has a custom repo associated, the collection is fairly useless without the repo.
So if you add a collection (a) into a collection (b), then a user can only use it when the user has access to collection (a), as such if collection (a) has a custom repo, that will also be used.

Second, only if collection (b) has a server connected, that server will be used. The server from collection (a) is not disconnected, but will simply be ignored. In other words, it is the server info from the parent collection that is relevant.

```
collection b (server used)
      \ - collection a (server ignored)
        - collection c (server ignored)
        - mod a
       - mod b
```
