### ISSUE TITLE
Add Content hosting for API Games

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#9]
Authors should be able to directly upload and host their content on our network. 

- [x] Publishing
- [x] Client should be able to download them

**Comment by sickboy** [comment]
@Sonsalt you do file based upload, but you must select a unique package-name, which translates to a download folder. On steam this is the id of the content.

Again something can't be a bug when you did not ask for the functionality in the first place. So please confirm that uploading works and installing works, and then create a new feature request card for other things.

**Comment by Sonsalt** [comment]
@sickboy copy will pull out and create new ticket.

http://staging.withsix.com/p/Starbound/mods/VYeMswCG60aYy4RGS6cG9A/testmodstarboungone
Download for new mod failed
I uploaded the mod into a folder, using the form. The file is a pak file.

**Comment by sickboy** [comment]
Missing was the RemoteInfo setup for the games in the client, and the mirrors needed to be updated (both should be streamlined in the future for quicker expansion :D)

**Comment by Sonsalt** [comment]
Feedback:

Download Works, but when launching it does not appear in the mod section within the game. 

The mod is installed to: C:\Program Files (x86)\Steam\SteamApps\workshop\content\211820\@testmodstarboundone extrazoomlevels.pak

**Comment by sickboy** [comment]
@Sonsalt thats great news! The name format of the pak file should be 'contents.pak'.
We could perhaps support the full name.pak's too, but currently we don't :)

**Comment by Sonsalt** [comment]
@sickboy I guess for the Starbound mods the .pak files have to be unique.

**Comment by sickboy** [comment]
@Sonsalt no, the files are in their own folder

**Comment by Sonsalt** [comment]
.pak works, will create a new ticket for the folder upload. We might need to pack them :)

**Comment by Sonsalt** [comment]
@sickboy https://github.com/SIXNetworks/withSIX-Platform/issues/93 here is the new ticket
