### ISSUE TITLE
Implement logos/banners for the tri-games

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX-Platform#92]
Implement Logo banners for Games

Implementation Feedback:

- [x] https://gyazo.com/01d3500dffac36745c4895adbe672b20 Stellaris Text in Search bar is too big:
- [ ] https://gyazo.com/c4cd5e2bff9e9c34c03afcfb1480ac7d Icons in Switch game are hard to read
- [x] https://gyazo.com/931580569312d013ed79b8b7ee14f357 skyrim icon in search bar is cut off

16:9 size adaption for all logos,

@sickboy here are all game logos and headers: https://www.dropbox.com/sh/qyymvemo78mqbug/AADgS-b6i0Wv03xjXjupBtU1a?dl=0 

If you miss anything let me know. (a file list and checkboxes would help)

**Comment by ParaGraphicL** [comment]
Skyrim


![skyrim-logo-white-emblem](https://cloud.githubusercontent.com/assets/1974880/17463091/42a436ac-5cbf-11e6-8028-68a191e4cf43.png)
![skyrim-boxart](https://cloud.githubusercontent.com/assets/1974880/17463093/42e7e53c-5cbf-11e6-8c2d-180da4693b29.png)
![skyrim-header](https://cloud.githubusercontent.com/assets/1974880/17463094/4311963e-5cbf-11e6-84af-3cda9b98b634.png)
![skyrim-logo-overview](https://cloud.githubusercontent.com/assets/1974880/17463095/4312d076-5cbf-11e6-9afe-278a1ef04c7d.png)
![skyrim-logo-white](https://cloud.githubusercontent.com/assets/1974880/17463096/43151b4c-5cbf-11e6-964c-17b0942193c7.png)

**Comment by ParaGraphicL** [comment]
Here are all game logos: https://www.dropbox.com/sh/qyymvemo78mqbug/AADgS-b6i0Wv03xjXjupBtU1a?dl=0

**Comment by sickboy** [comment]
@Sonsalt I shouldn't be assigned here.

>  Game Selector page Banners missing
No, the games are missing from the game selector page because they are not considered public.

**Comment by ParaGraphicL** [comment]
@Sonsalt 

>  https://gyazo.com/01d3500dffac36745c4895adbe672b20 Stellaris Text in Search bar is too big
Size is in line with other logo's regarding height

> https://gyazo.com/c4cd5e2bff9e9c34c03afcfb1480ac7d Icons in Switch game are hard to read
Size seem to be squeezed in, but other then that I can't see how we would fix this 

> https://gyazo.com/931580569312d013ed79b8b7ee14f357 skyrim icon in search bar is cut off
Image isn't cut off, why would you think this?

**Comment by sickboy** [comment]
@Sonsalt ?

**Comment by Sonsalt** [comment]
@ParaGraphicL sorry just saw your comment, ....

- Stellaris text
the issue is that in the search bar it takes almost 1/3 of the entire bar, this really feels big

- Icons in Switch game:
Starbound is ok, but skyrim for example really looks cut off. 

- Skyrim image in search cut off. 
It feels cut off due do the different shades of blue.

**Comment by sickboy** [comment]
@Sonsalt so what is the plan now?

**Comment by Sonsalt** [comment]
@sickboy you had a conversation with Sven during our meeting, something about making the icons bigger and place them in the middle. 

Did he want to give you new ones?

the other Items I ticked off for now

**Comment by sickboy** [comment]
@Sonsalt aha, hm, something about documenting our actionable items :P
