### ISSUE TITLE
ACR_A3 - Army of the Czech Republic Update fails unknown reason

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#96]
http://withsix.com/p/Arma-3/mods/xCWb8Tox5BG9NQAVF72WTA/ACR-A3-Army-of-the-Czech-Republic

Updating this mod fails via all sources: 

https://forums.bistudio.com/topic/172582-army-of-the-czech-republic-a3-acr-a3/page-9#entry3075980

Evro already tried via local, Google and GIT, I tried Steam all fail, 

I can not figure out why.

**Comment by sickboy** [comment]
The log said that there was a file not deletable. I've deleted the relevant files and also removed all these legacy .rsync folders from the other older mods.
