### ISSUE TITLE
Finalize and Publish Playlist tutorial Video

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#97]
- [x] Finalize Playlist video

- [x] Publish Video on youtube
- [x]  Publish on FB
- [x] Publish in Blog
- [ ] Publish in Twitter

**Comment by ParaGraphicL** [comment]
Blog gif: http://gfycat.com/PositiveElegantBengaltiger 

MP4-link: 

Youtube:

**Comment by Sonsalt** [comment]
@ParaGraphicL now it is just about when we release, thanks :)

**Comment by Sonsalt** [comment]
Video partially released, waiting for a fix on the Collection PL search before pushing on Twitter and FB

**Comment by sickboy** [comment]
@Sonsalt Please refer issues. #129
